import localFont from "next/font/local";
import "./globals.css";
import AppProviders from "@/components/AppProvider/app-provider";
import { ExternalLinkProvider } from "@/hooks/useExternalLink";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Unswayed-web app",
  description: "Generated by Unswayed team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppProviders>
          <ExternalLinkProvider>{children}</ExternalLinkProvider>
        </AppProviders>
      </body>
    </html>
  );
}
