export const EMPLOYER_APPLICATION_DETAILS =  [
    { title: "UCN", name: "ucn", type:'application'},
    { title: "Position Title", name: "title", type:'job'},
    { title: "Employment Type", name: "job_type", type:'job'},
    { title: "Employment Location", name: "job_location", type:'job'},
    { title: "Employment Category", name: "job_category", type:'job'},
    { title: "Employment Shift", name: "job_shift", type:'job'},
    { title: "Are You 18 Years or Older?", name: "is_adult", type:'application'},
    { title: "Are You a Veteran", name: "is_veteran", type:'application'},
    { title: "Are You a US Citizen Authorized to Work in the United States?", name: "authorized_to_work", type:'application'},
    { title: "Do You Have a work Visa or will you require one in the future?", name: "have_visa", type:'application'},
    { title: "Do You Meet the Must Have Qualifications?", name: "meet_qualifications", type:'application'},
    { title: "Do You Meet the Education Requirements?", name: "meet_educations", type:'application'},
    { title: "Do You Have Any Disability", name: "have_disability", type:'application'},
]