export const USERS = [
  {
    id: 1,
    first_name: "John",
    middle_name: "M.",
    last_name: "Doe",
    username: "JohnDoe123",
    type: "applicant",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 12,
    applicant_id: 10,
  },
  {
    id: 2,
    first_name: "Jane",
    middle_name: "A.",
    last_name: "Smith",
    username: "JaneSmith456",
    type: "employer",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 30,
    employer_id: 15,
  },
  {
    id: 3,
    first_name: "Robert",
    middle_name: "J.",
    last_name: "Brown",
    username: "RobbyB",
    type: "applicant",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 5,
    applicant_id: 8,
  },
  {
    id: 4,
    first_name: "Emily",
    middle_name: "K.",
    last_name: "Davis",
    username: "EmilyKDavis",
    type: "employer",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 22,
    employer_id: 20,
  },
  {
    id: 5,
    first_name: "David",
    middle_name: "L.",
    last_name: "Miller",
    username: "DaveMiller",
    type: "applicant",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 8,
    applicant_id: 14,
  },
  {
    id: 6,
    first_name: "Sophia",
    middle_name: "R.",
    last_name: "Garcia",
    username: "SophiaRG",
    type: "applicant",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 16,
    applicant_id: 18,
  },
  {
    id: 7,
    first_name: "James",
    middle_name: "P.",
    last_name: "Martinez",
    username: "JamesPMartinez",
    type: "employer",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 10,
    employer_id: 13,
  },
  {
    id: 8,
    first_name: "Isabella",
    middle_name: "T.",
    last_name: "Hernandez",
    username: "IsabellaH",
    type: "applicant",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 11,
    applicant_id: 25,
  },
  {
    id: 9,
    first_name: "Daniel",
    middle_name: "B.",
    last_name: "Lopez",
    username: "DannyLopez",
    type: "employer",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 27,
    employer_id: 30,
  },
  {
    id: 10,
    first_name: "Olivia",
    middle_name: "V.",
    last_name: "Clark",
    username: "OliviaClark",
    type: "applicant",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 19,
    applicant_id: 22,
  },
  {
    id: 11,
    first_name: "Matthew",
    middle_name: "Q.",
    last_name: "Lee",
    username: "MattLee",
    type: "employer",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 14,
    employer_id: 9,
  },
  {
    id: 12,
    first_name: "Mia",
    middle_name: "E.",
    last_name: "Walker",
    username: "MiaWalker",
    type: "applicant",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 7,
    applicant_id: 17,
  },
  {
    id: 13,
    first_name: "Ethan",
    middle_name: "Z.",
    last_name: "Hall",
    username: "EthanZHall",
    type: "applicant",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 9,
    applicant_id: 28,
  },
  {
    id: 14,
    first_name: "Charlotte",
    middle_name: "F.",
    last_name: "Allen",
    username: "CharlotteFA",
    type: "employer",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 12,
    employer_id: 6,
  },
  {
    id: 15,
    first_name: "Alexander",
    middle_name: "H.",
    last_name: "Young",
    username: "AlexYoung",
    type: "applicant",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 3,
    applicant_id: 12,
  },
  {
    id: 16,
    first_name: "Amelia",
    middle_name: "N.",
    last_name: "King",
    username: "AmeliaKing",
    type: "applicant",
    isFollowed: false,
    photo: "/assets/images/talentNetwork/icon.png",
    followers_count: 20,
    applicant_id: 24,
  },
];
export const SEARCHABLE_RALLIs = {
  jobTitle: "Software Engineer ",
  time: "01:50 AM",
  date: "01/10/2010",
  UCN:'62453',
  status:'Pending',
  JobDescriptions:
    "This job has only on software field This job has only on software field This job has only on software field This job has only on software field This job has only on software field This job has only on software field This job has only on software field This job has only on software field This job has only on software field This job has only on software field",

  boxData: [
    {
      id: 1,
      ucNumber: "UCN NUMBER",
      title: "interview invite by empolyer  ",
      buttonLable: "Offer Latter",
      type:'OfferLetter'
      // para: "Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled. Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled lorem lipsum dolor sir amir dummy text.",
    },
    {
      id: 2,
      ucNumber: "UCN NUMBER",
      title: "interview decline  ",
      buttonLable: "Offer Latter",
      type:'CounterOfferLetter'

      // para: "Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled. Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled lorem lipsum dolor sir amir dummy text.",
    },
    {
      id: 3,
      ucNumber: "UCN NUMBER",
      title: "interview decline  ",
      buttonLable: "Offer Latter",
      type:'Interview'

      // para: "Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled. Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled lorem lipsum dolor sir amir dummy text.",
    },
  ],
};
export const MY_ACTIVITIES_JSON = {
  pages: "Build Your Resume (4 Of 4)",
  title: "want to allow employers to you on ralli??",

  boxData: [
    {
      id: 1,
      ucNumber: "UCN NUMBER",
      title: "Interview Accept ",
      buttonLable: "Further Details",
      time: "01:50 AM",
      date: "01/10/2010",
      para: "Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled. Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled lorem lipsum dolor sir amir dummy text.",
    },
    {
      id: 2,
      ucNumber: "UCN NUMBER",
      title: "Interview Invite by Employer ",
      buttonLable: "Further Details",
      time: "01:50 AM",
      date: "01/10/2010",
      para: "Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled. Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled lorem lipsum dolor sir amir dummy text.",
    },
    {
      id: 3,
      ucNumber: "UCN NUMBER",
      title: "Interview Decline",
      buttonLable: "Further Details",
      time: "01:50 AM",
      date: "01/10/2010",
      para: "Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled. Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled lorem lipsum dolor sir amir dummy text.",
    },
    {
      id: 4,
      ucNumber: "UCN NUMBER",
      title: "Applicant Submitted",
      buttonLable: "Further Details",
      time: "01:50 AM",
      date: "01/10/2010",
      para: "Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled. Lorem Ipsum is simply dummy text of printing & typesetting industry. Lorem Ipsum has been the industry sxzc standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled lorem lipsum dolor sir amir dummy text.",
    },
  ],
};
