export const CREATE_JOB_FORM = {
  form: [
    {
      title: "External Job Link (optional)",
      name: "job_apply_link",
      placeHolder: "URL to personal job link from your website. Eg: https://company.com/careers/job",
      type: "url",
      ai: false,
      required: false,
    },
    {
      title: "Job Title",
      name: "title",
      placeHolder: "Job Title",
      type: "text",
      required: true,
    },
    {
      title: "Number Of Positions To Be Filled",
      name: "no_of_positions",
      placeHolder: "0",
      type: "number",
      required: true,
    },
    {
      title: "Application Deadline",
      name: "deadline",
      placeHolder: "Select Deadline",
      type: "date",
      required: true,
    },
    {
      title: "Experience",
      name: "experience_level",
      placeHolder: "senior",
      type: "dropdown",
      required: true,
    },
    {
      title: "Job Category",
      name: "job_categories",
      placeHolder: "Select Category",
      type: "dropdown",
      required: true,
    },
    {
      title: "Job Type",
      name: "job_types",
      placeHolder: "Select Type",
      type: "dropdown",
      required: true,
    },
    {
      title: "Job Location",
      name: "job_locations",
      placeHolder: "Select Location",
      type: "dropdown",
      required: true,
    },
    {
      title: "Job Shift",
      name: "job_shifts",
      placeHolder: "Select Shift",
      type: "dropdown",
      required: true,
    },
    {
      title: "Shift Hours",
      name: "job_shift_timing",
      placeHolder: "8",
      type: "dropdown",
      required: true,
    },
    {
      title: "Country",
      name: "country",
      placeHolder: "Select Country",
      type: "dropdown",
      required: true,
    },
    {
      title: "State",
      name: "states",
      placeHolder: "Select State",
      type: "dropdown",
      required: true,
    },
    {
      title: "City",
      name: "cities",
      placeHolder: "Select City",
      type: "dropdown",
      required: true,
    },
    {
      title: "Skills",
      name: "skills",
      placeHolder: "Press Enter To Add Skills",
      type: "taginput",
      required: true,
    },
    {
      title: "Minimum Salary",
      name: "salary",
      placeHolder: "Minimum Salary",
      type: "number",
      required: true,
    },
    {
      title: "Maximum Salary",
      name: "salary_max",
      placeHolder: "Maximum Salary",
      type: "number",
      required: true,
    },
    {
      title: "Salary Period",
      name: "salary_period",
      placeHolder: "Per Annum",
      type: "dropdown",
      required: true,
    },
    {
      title: "Salary Currency",
      name: "salary_currency",
      placeHolder: "USD",
      type: "dropdown",
      required: true,
    },
    {
      title: "Interview Rounds",
      name: "interview_rounds",
      placeHolder: "Interview Rounds",
      type: "number",
      required: false,
    },
    {
      title: "About The Company",
      name: "company_about",
      placeHolder: "About Your Company",
      type: "textarea",
      required: true,
    },
    {
      title: "Benefits",
      name: "company_benefits",
      placeHolder: "Benefits",
      type: "dropdown",
      required: false,
    },
    {
      title: "Job Requirements",
      name: "requirements",
      placeHolder: "Requirements for this job",
      type: "textarea",
      ai: true,
      required: true,
    },
    {
      title: "Job Description",
      name: "description",
      placeHolder: "Description for job",
      type: "textarea",
      ai: true,
      required: true,
    },
    
  ],
};
